[package]
name = "stl-syncer"
version = "0.1.0"
edition = "2024"

[dependencies]
tauri = { version = "2" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11", features = ["json", "gzip"] }
rusqlite = "0.31"
ring = "0.17"
tauri-plugin-store = "2"
